namespace Template {
    export let text = {
        bonny: {
            scene1: {
                T0001: "...",
                T0002: "Where am I?",
                T0003: "Why is everything so bright?",
                T0004: "Hello… Is anyone here?",
                T0005: "Hello? Can you see me?",
                T0006: "What does this mean? Am I...",
                T0007_1: "That can't be true! How can it be?",
                T0007_2: "You said there must have been a mistake! So just take me back!",
                T0008: "Please... Listen...",
                T0009: "Finally, for once in my life I was happy. I found the love of my life. I can't lose him so soon. I need to see him again. I beg you...",
                T0010: "Why are you telling me all of this? How does that help me now?",
                T0011_1: "Okay, sounds good! But how do I know, which memory to choose? There are so many...",
                T0011_2: "...and I somehow feel like I forgot most of them.",
                T0012: "Alright, Bo. I trust you! I am ready."
          },
          scene2: {
                T0000: "...",
                T0001: "Did it work? I think so, right?",
                T0002: "I know this place! ",
                T0003: "It's my room! But how can it be just a memory?",
                T0004: "Everything feels so real right now.",
                T0005: "I wish Bo was still here to help me.",
                T0006: "How am I supposed to figure this out on my own? ",
                T0007: "Out of all the possibilities, why did I got send back to this memory?",
                T0008: "Oh my god! Nat!",
                T0009: "Of course! I have to find him!",
                T0010: "I need to tell him that I love him. That I need him.",
                T0011: "Maybe I haven't told him that as much lately and that's why I ended up in this mess.",
                T0012: "Bo said I should live my life as usually, but I slowly feel like forgetting everything from my past life.",
                T0013: "I don't know what I usually do anymore.",
                T0014: "Maybe I should look around my room for a bit to find something that helps me remember.",
                T0015: "Oh, look at this mess. I don't think that this helps me right know.",
                T0016: "But wait! My journal! I wrote up what I am supposed to do today!",
                T0017: "Mhh alright... apparently, I didn't plan so much for today.",
                T0018: "Maybe I should just work on those things for now than.",
                T0019: "Wow, memories inside of a memory... how ironic.",
                T0020: "I wish I could've gone back to one of those instead of being stuck in this room.",
                T0021: "Ugh, I don't like when the weather gets so gloomy! It looks like it will begin to rain soon.",
                T0022: "Okay, maybe getting out of my room would actually help a bit more. I should get ready to run my errands. Good thing, that I wrote a shopping list as well.",
                T0023: "This seems very important. I should get to work now!",
                T0024: "That was a lot of work! I hope it was worth it!",
                T0025: "I am really hungry right now. Good thing, that this is on the list as well!",
                T0026: "Mhh.. that was delicious. I needed that really badly right now."
          },
          scene3_1: {
                T0001: "Alright! I guess I'll just grab those few things on my shopping list and return back home then.",
                T0002: "I still don't understand how this would help me now though.",
                T0003: "Okay, I bought everything I needed. Time to get back home.",
                T0004: "As she arrived back to her room, Bonny started ticking off the tasks of her To-Do-List. Trusting Bo in the decisions that were made, she began to work on her project for school and started cooking something delicious. After a long day of living her life as usual, she fell into bed. Exhausted from the work that she did, she forgot what brought her here in the first place. And so, she began to drift off into her dreams. Dreams of bright and happy memories - hoping that they'll last forever."
          },
          scene3_2: {
                T0001: "Those things won't matter anyway, if I don't find Nat soon.",
                T0002: "I feel like I am running out of time. I should hurry!",
                T0003: "I'm sorry. I didn't see you there...",
                T0004: "Oh my god! Is that you?",
                T0005: "It has to be, right? But why would he not recognize me?",
                T0006: "I don't remember bumping into him like that in the past... did I miss something?",
                T0007: "Did I do something wrong... Why would-",
                T0008: "Oh, I didn't mean to say those things out loud.",
                T0009: "Anyway... you are Nathan, right?",
                T0010: "Oh... mhh... ehh...",
                T0011: "Ah right! I know you from university!",
                T0012: "We're both in this one class! It's called...",
                T0013: "No! Don't worry! I am sorry. I should've watched out...",
                T0014: "Yes! Sounds good, I would love that!",
                T0015: "We could go to our favourite place and-",
                T0016: "Oh wait! You don't remember anyway...",
                T0017: "I'm sorry... how about you choose a place where we could go to?",
                T0018: "Yes sure!",
                T0019: "See you!",
                T0020: "Alright, that was nice... but also weird!",
                T0021: "How come that he doesn't know me?! Is that a memory from the time before we were friends?",
                T0022: "Maybe... from the time when I first moved to this city?",
                T0023: "Ugh, I hate that I don't remember my past!",
                T0024: "How am I supposed to find the mistake, when I don't know if I am doing the right things here either?",
                T0025: "Okay, I should get back home now and prepare myself for the evening with Nat.",
                T0026: "As she arrived back home, Bonny tossed her new bought groceries into the kitchen and started to get ready for the evening. Nat did message her the location and it was in fact the place they both used to visit a lot together. Bonny started to feel like Bo only had good intentions in mind, by letting her relive these precious moments again."
          },
          scene3_3: {
                T0001: "Ugh shoot, I forgot to bring an umbrella!",
                T0002: "I hate the rain!",
                T0003: "I should hurry to get inside!",
                T0004: "Just quickly across the street...",
                T0005: "AHHH!!!"
          },
          scene4: {
                T0001: "*zzz* *zzz*",
                T0002: "Oh, is it the next day already?",
                T0003: "Am I still in a memory?",
                T0004: "I think so right?",
                T0005: "Bo didn't bring me back to him. What am I supposed to do now?",
                T0006: "...",
                T0007: "“Living my life as I would usually do.”",
                T0008: "That means I have to go to school, right?",
                T0009: "...",
                T0010: "Oh my god! I have to go to school!",
                T0011: "I'm already late!",
                T0012: "I'm just grabbing everything I need and then I gotta...",
                T0013: "Alright, since school isn't so far away, I'll just run over there.",
                T0014: "I don't want to waste any more time. I'll grab the bike and drive to school real quick!",
                T0015: "Oh shoot! The first half of the lecture is already over!",
                T0016: "I need to hurry up before I-",
                T0017: "I'm sorry. I didn't see you there… ",
                T0018: "Oh my god! Is that you?",
                T0019: "It has to be, right? But why would he not recognize me? ",
                T0020: "I don't remember bumping into him like that… did I miss something? ",
                T0021: "Did I do something wrong… Why would-",
                T0022: "Oh, I didn't mean to say those things out loud.",
                T0023: "Oh… yes… of course!",
                T0024: "I'm sorry. I should have watched out. ",
                T0025: "I'm just stressed because I'm to late to my class.",
                T0026: "Oh I think it's called...",
                T0027: "Oh really?! I didn't notice that.",
                T0028: "Yes! That would be great!"
          }
        },
        unknownBo: {
            scene1: {
                T0000: "...",
                T0001: "Oh yes, of course I can see you.",
                T0002: "That's what irritates me so much.",
                T0003: "I should not be able to see you.",
                T0004: "You see... I didn't expect you for at least many many years later. I am just surprised to find you here all of the sudden.",
                T0005: "I am you. But well, not really. I am Bo... your spirit animal. I guide you and try my best to protect you.",
                T0006: "That I still don't know. There must be a mistake... You just appeared in front of me."
            }
          },
        bo : {
            scene1: {
                T0001: "...dead?",
                T0002: "Okay, please don't freak out, but you're sort of in the afterlife right now.",
                T0003_1: "That means your life has somehow come to an end... but your soul is still trapped between life and death.",
                T0003_2: "In order to get you to the other side, you have to let go of your life. Otherwise, you will be trapped in this room forever.",
                T0003_3: "Only you can make that decision.",
                T0004: "It's not that easy, I...",
                T0005: "Okay okay, just let me think for a short moment...",
                T0006: "Oh, there might actually be a small chance of this working.",
                T0007_1: "You probably heard about the myth, that you see your life flashing by when you're dying...",
                T0007_2: "...well, it's kind of true.",
                T0008: "Here in the afterlife, we can revisit our dearest memories. Watching our lives passing by from a distance. Seeing those memories can help us to find closure and get ready to let go of everything.",
                T0009: "Sometimes though we regret certain decisions we made in the past. Here you could also make different desicions to see what would have happened instead. Just like in a simulation.",
                T0010: " It would help you a lot actually! If I transfer you back in your memories, you could relive everything and find out what brought you here.",
                T0011: "If we find the mistake, you don't need to stay here any longer and I will bring you back to life.",
                T0012: "Yeah, ironically memory loss is one of the side effects of being in the afterlife.",
                T0013: "That's why you don't get to choose the memories to relive.",
                T0014_1: "Remember? I am you.",
                T0014_2: "I know you. Your wishes, your dreams, your desires... That's why I am here with you. You just have to trust me.",
                T0015: "Alright, as soon as you are in the memory, you can't communicate with me anymore. Just live your life like you would usually do.",
                T0016: "As soon as we find the mistake, I will bring you back to me.",
                T0017: "See you soon!"
            }
        },
        unknownNat: {
            scene3_1: {
                T0001: "Ouch! You should watch where you're going!",
                T0002: "What? Do I know you?",
                T0003: "Hello? What are you talking about?!"
            }
        },
        nat: {
            scene3_1: {
                T0001: "Yes, I am… but everyone just calls me Nat.",
                T0002: "How do you know that?! I've never met you?!",
                T0003: "Mhh okay… ",
                T0004: "Well, sorry… I don't remember you. ",
                T0005: "But must be true than!",
                T0006: "Listen, I didn't mean to be rude to you… I-",
                T0007: "Hey, how 'bout we're not being sorry for each other and make it right by grabbing something to drink later in the evening?",
                T0008: "Sure! Let me just take your phone number and I'll text you the location later, okay?",
                T0009: "'Kay, see ya!"
            },
            scene4: {
                T0001: "I'm Nathan… But well everyone calls me Nat, if that clears things up for you.",
                T0002: "And yes, I don't recognize you, because I don't know you.",
                T0003: "And at least you could apologize for running into me like that.",
                T0004: "Oh really? ",
                T0005: "Then you don't need to be sorry, because I'm running late to my class as well!",
                T0006: "Which class are you taking?",
                T0007: "You're kidding right?",
                T0008: "That's the one I'm supposed to have right now!",
                T0009: "But it looks like you were walking in the totally wrong direction.",
                T0010: "'Kay, before we waste any more time… How 'bout we rush over there together?"
            }
        }
    };
}